#ifndef RISA_DEF_H_GUARD
#define RISA_DEF_H_GUARD

#include <float.h>

#include "macro.h"

#define RISA_KILOBYTE 1024
#define RISA_VALUE_FLOAT_MIN DBL_MIN

#define RISA_MATH_PI 3.14159265358979323846
#define RISA_MATH_E  2.71828182845904523536

#define RISA_MATH_RAD2DEG  (180 / RISA_MATH_PI)
#define RISA_MATH_DEG2RAD  (RISA_MATH_PI / 180)

#ifndef RISA_VM_CALLFRAME_COUNT
    #define RISA_VM_CALLFRAME_COUNT 64
#endif

#ifndef RISA_VM_CALLFRAME_STACK_SIZE
    #define RISA_VM_CALLFRAME_STACK_SIZE 251
#endif

#ifndef RISA_VM_STACK_SIZE
    #define RISA_VM_STACK_SIZE (RISA_VM_CALLFRAME_COUNT * RISA_VM_CALLFRAME_STACK_SIZE)
#endif

#ifndef RISA_VM_HEAP_INITIAL_THRESHOLD
    #define RISA_VM_HEAP_INITIAL_THRESHOLD (64 * RISA_KILOBYTE)
#endif

#ifndef RISA_INPUT_WORD_BUFFER_SIZE
    #define RISA_INPUT_WORD_BUFFER_SIZE 128
#endif

#ifndef RISA_INPUT_LINE_BUFFER_SIZE
    #define RISA_INPUT_LINE_BUFFER_SIZE 1024
#endif

#ifndef RISA_VALUE_FLOAT_PRECISION
    #include <float.h> // For DECIMAL_DIG
    #define RISA_VALUE_FLOAT_PRECISION 15 //DECIMAL_DIG
#endif

#ifndef RISA_VALUE_FLOAT_ZERO_THRESHOLD
    #define RISA_VALUE_FLOAT_ZERO_THRESHOLD RISA_CONCAT(1e-, RISA_VALUE_FLOAT_PRECISION) // 1e-15
#endif

//#define DEBUG_TRACE_MEMORY_OPS
//#define DEBUG_SHOW_HEAP_SIZE

#endif
