#ifndef RISA_DEF_H_GUARD
#define RISA_DEF_H_GUARD

#define RISA_KILOBYTE 1024

#define CALLFRAME_STACK_SIZE 64
#define VM_STACK_SIZE CALLFRAME_STACK_SIZE * 251
#define VM_HEAP_INITIAL_THRESHOLD (64 * RISA_KILOBYTE)

//#define DEBUG_TRACE_EXECUTION
//#define DEBUG_TRACE_MEMORY_OPS
//#define DEBUG_SHOW_DISASSEMBLY
//#define DEBUG_SHOW_HEAP_SIZE

#endif
