#ifndef RISA_VERSION_H_GUARD
#define RISA_VERSION_H_GUARD

#define RISA_VERSION_MAJOR 0
#define RISA_VERSION_MINOR 0
#define RISA_VERSION_PATCH 0x42
#define RISA_VERSION_SIGNATURE ((RISA_VERSION_MAJOR << 24) | (RISA_VERSION_MINOR << 16) | (RISA_VERSION_PATCH & 0xFFFF))

#define RISA_VERSION_STRING "0.0.B"
#define RISA_VERSION_CODENAME "PREVIEW"

#endif
