#ifndef RISA_DEF_H_GUARD
#define RISA_DEF_H_GUARD

#define CALLFRAME_STACK_SIZE 64

//#define DEBUG_TRACE_EXECUTION
//#define DEBUG_TRACE_MEMORY_OPS
//#define DEBUG_SHOW_DISASSEMBLY
//#define DEBUG_SHOW_HEAP_SIZE

#endif
